// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TollFeeCalculator.utils;

namespace afryCodeTest.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25");

            modelBuilder.Entity("TollFeeCalculator.Vehicle", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("LicensePlate");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("TollFeeCalculator.models.Fee", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeeAmount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("FeeDayid")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("FeeHourid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleLicensePlate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeeDayid");

                    b.HasIndex("FeeHourid");

                    b.HasIndex("VehicleLicensePlate");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("TollFeeCalculator.models.FeeDay", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Day")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("FeeDay");
                });

            modelBuilder.Entity("TollFeeCalculator.models.FeeHour", b =>
                {
                    b.Property<ulong>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeeAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("FeeHour");
                });

            modelBuilder.Entity("TollFeeCalculator.models.Fee", b =>
                {
                    b.HasOne("TollFeeCalculator.models.FeeDay", "FeeDay")
                        .WithMany()
                        .HasForeignKey("FeeDayid");

                    b.HasOne("TollFeeCalculator.models.FeeHour", "FeeHour")
                        .WithMany()
                        .HasForeignKey("FeeHourid");

                    b.HasOne("TollFeeCalculator.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleLicensePlate");
                });
#pragma warning restore 612, 618
        }
    }
}
