version: "3"
services:
  api-service:
    image: padmasankha/toll-fee-api-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000" # HTTP
    restart: on-failure
