/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import calculator.command.CommandInterpreter;
import calculator.command.commands.Command;
import calculator.exceptions.IllegalFileFormatException;
import lombok.extern.slf4j.Slf4j;
import java.util.ArrayList;
import java.util.List;

@Slf4j
public class App
{
private App(){}

    static void start(String[] args) throws IllegalFileFormatException
    {
        System.out.println("Starting... ");
        List<String> argsList;
        if (args == null || args.length == 0)
        {
            System.out.println("No arguments provided. Processing demo data. ");
            argsList = new ArrayList<>();
        }
        else argsList = List.of(args);
        Command command = CommandInterpreter.interpret(argsList);
        if (command.execute()) log.info("Succeeded executing command. ");

    }

    public static void main(String[] args)
    {
        try
        {
            start(args);
        } catch (IllegalFileFormatException ex)
        {
            System.out.println("TollCalculator closing down with error message: " + ex.getMessage());
            System.exit(1);
        }
    }
}
